pub_twist_cmd: true
debug_info: false
delay_mode: false
max_speed: 0.6
waypoints_dist: -1
path_length: 1
goal_radius: 0.0
controller_freq: 12
mpc_steps: 16.0
mpc_ref_cte: 0.01
mpc_ref_vel: 1
mpc_ref_etheta: 0.1
mpc_w_cte: 2500.0
mpc_w_etheta: 1000.0
mpc_w_vel: 2000.0
mpc_w_angvel: 0.01
mpc_w_angvel_d: 10
mpc_w_accel: 10
mpc_w_accel_d: 1
mpc_max_angvel: 1
mpc_max_throttle: 0.9
mpc_bound_value: 1.0e3
